version: '3.8'
services:
  db:
    image: mysql:5.6
    container_name: sqldiffer
    environment:
      MYSQL_ROOT_PASSWORD: thisistest
    ports:
      - '127.0.0.1:33066:3306'
    volumes:
      - './docker/mysql/initdb.d:/docker-entrypoint-initdb.d'
